backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "reports"
    label: "Research Reports"
    folder: "content/reports"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Macroeconomic", "Political Economy", "Portfolio Strategy", "Market Analysis", "Geopolitical"]}
      - {label: "Summary", name: "summary", widget: "text", hint: "Brief summary of the report (up to 500 characters)", pattern: [".{1,500}", "Summary must be between 1 and 500 characters"]}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "PDF File", name: "pdf", widget: "file", required: false}

  - name: "portfolio"
    label: "Portfolio Strategy"
    files:
      - name: "current-positioning"
        label: "Current Market Positioning"
        file: "content/portfolio/current-positioning.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Last Updated", name: "date", widget: "datetime"}
          - {label: "Market Outlook", name: "outlook", widget: "text"}
          - label: "Asset Allocation"
            name: "allocation"
            widget: "list"
            fields:
              - {label: "Asset Class", name: "asset", widget: "string"}
              - {label: "Percentage", name: "percentage", widget: "number"}
              - {label: "Color", name: "color", widget: "color"}
          - label: "Key Performance Metrics"
            name: "metrics"
            widget: "object"
            fields:
              - {label: "Annual Return", name: "annual_return", widget: "string"}
              - {label: "Sharpe Ratio", name: "sharpe_ratio", widget: "string"}
              - {label: "Volatility", name: "volatility", widget: "string"}
              - {label: "Max Drawdown", name: "max_drawdown", widget: "string"}
              - {label: "Beta", name: "beta", widget: "string"}
              - {label: "Alpha", name: "alpha", widget: "string"}
          - label: "Positioning Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - {label: "Icon", name: "icon", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}

  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings.md"
        fields:
          - {label: "Company Name", name: "company_name", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
